function l(b,a,c,d){b.v.Hb(b.mb,a,c,d,void 0)}function m(b,a,c,d){b.v.ca?l(b,a,c,d):b.v.ze()._OnMessageFromDOM({type:"event",component:b.mb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.v.C(b.mb,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}function aa(b){b.Sb||(b.v.md(b.Td),b.Sb=!0)}window.fb=class{constructor(b,a){this.v=b;this.mb=a;this.Sb=!1;this.Td=()=>this.Na()}cd(){}Na(){}};
window.gf=class{constructor(){this.$c=-1}j(){-1!==this.$c&&(self.clearTimeout(this.$c),this.$c=-1)}};"use strict";class ba{constructor(b){this.Ic=b;this.Lc=!1;this.Sc=!0}}function ca(b,a){const c=a.elementId,d=b.eb(c,a),e=new ba(d);b.pb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Sc=!!a.isVisible;a=b.xc(d);a.addEventListener("focus",()=>{da(b,"elem-focused",c)});a.addEventListener("blur",()=>{da(b,"elem-blurred",c)});b.Ob&&document.body.appendChild(d)}
function t(b,a,c){q(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.pb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ic}function da(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}function w(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}
window.Fb=class extends self.fb{constructor(b,a){super(b,a);this.pb=new Map;this.Ob=!0;r(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=v(this,c);this.hd(d);this.Ob&&d.parentElement.removeChild(d);this.pb.delete(c)}],["set-visible",c=>{if(this.Ob){var d=this.pb.get(c.elementId),e=d.Ic;d.Lc?e.style.display=c.isVisible?"":"none":d.Sc=!!c.isVisible}}],["update-position",c=>{if(this.Ob){var d=this.pb.get(c.elementId),e=d.Ic;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Lc||(d.Lc=!0,d.Sc&&(e.style.display=""))}}],["update-state",c=>{const d=v(this,c.elementId);this.Ea(d,c)}],["focus",c=>{const d=this.xc(v(this,c.elementId));c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,
c.elementId).removeAttribute(c.name)}]]);t(this,"get-element",c=>c)}eb(){throw Error("required override");}hd(){}Ea(){throw Error("required override");}xc(b){return b}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),fa=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ia=0;
function ja(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Xe?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.af+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ka=!1,la=!1;function ma(){if(!ka){try{new Worker("blob://",{get type(){la=!0}})}catch(b){}ka=!0}return la}let x=new Audio;
const na={"audio/webm; codecs=opus":!!x.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!x.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!x.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!x.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!x.canPlayType("audio/mp4"),"audio/mpeg":!!x.canPlayType("audio/mpeg")};x=null;async function pa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const ra=[];let y=0;window.RealFile=window.File;const A=[],sa=new Map,va=new Map;let wa=0;const xa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");xa.push(b)};const ya=new Set(["cordova","playable-ad","instant-games"]);let za=!1;
window.oa=class b{constructor(a){this.ca=a.cf;this.xa=null;this.ba="";this.$a=a.$e;this.Db={};this.Ta=this.ua=null;this.Qb=[];this.H=this.ya=null;this.Pc=!1;this.Ad=0;this.sb=null;this.Za=-1;this.Se=()=>this.Ge();this.Ya=[];this.B=a.Ud;this.Ub="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ma()||(this.ca=!1);this.ca&&ha&&(this.ca=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ca=!1;if("cordova"===this.B&&this.ca)if(fa){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Xb=this.ra=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Ce(c));this.C("runtime","create-job-worker",()=>this.De());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.pd(a)):this.pd(a)}j(){this.vc();this.xa&&(this.xa=this.xa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Ta&&(this.Ta.j(),this.Ta=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}oe(){return ea&&"cordova"===this.B}rc(){const a=navigator.userAgent;return ea&&ya.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}me(){return fa}jd(){return fa&&ya.has(this.B)}async pd(a){"macos-wkwebview"===this.B&&this.Le();if("playable-ad"===this.B){this.ra=
self.c3_base64files;this.Xb={};await this.ve();for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Xb.hasOwnProperty(c)?a.bb[d]={Xe:!0,af:this.Xb[c]}:this.ra.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.ra[c]))}a.kc=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.md(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ze?this.ba=a.Ze:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=
this.ba.substr(0,c+1)));a.ef&&(this.Db=a.ef);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Fe(d));this.sb=new self.pe(this);await Aa(this.sb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.Be(a,c.port2):await this.Ae(a,c.port2)}yc(a){a=this.Db.hasOwnProperty(a)?this.Db[a]:a.endsWith("/workermain.js")&&this.Db.hasOwnProperty("workermain.js")?this.Db["workermain.js"]:"playable-ad"===this.B&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async mc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Ub)return a=await this.Eb(d.We?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}od(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.ib(),k=a.lf,n=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,D=window.cr_previewProjectFiles,z=window.jf||
"";a=a.Ud;var u=(new URLSearchParams(self.location.search)).has("debug"),E=this.sb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:D,swClientId:z,exportType:a,isDebug:u,ife:!!self.kf,jobScheduler:{inputPort:E.Oc,outputPort:E.Wc,maxNumWorkers:E.Pe},supportedAudioFormats:na,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.$a+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.oe(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Be(a,c){const d=this.yc(a.df);"preview"===this.B?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const n=p=>{this.ua.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():k()};this.ua.addEventListener("message",n);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ua=await this.mc(d,this.ba,{type:"module",name:"Runtime",We:!0});this.H=document.createElement("canvas");this.H.style.display="none";const e=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.kc||[],g=a.bb;f=await Promise.all(f.map(h=>this.Oa(h)));g=await Promise.all(g.map(h=>this.Oa(h)));if("cordova"===this.B)for(let h=0,k=a.jc.length;h<k;++h){const n=
a.jc[h],p=n[0];if(p===a.ad||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.Oa(p)}this.ua.postMessage(Object.assign(this.od(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.jc,mainProjectScript:a.ad,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Ba(this.sb)]);this.Qb=A.map(h=>new h(this));this.nd();Ca(this.ya);self.c3_callFunction=(h,k)=>{var n=this.ya;return n.v.ld(n.mb,"js-invoke-function",
{name:h,params:k},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Hb("runtime","go-to-last-error-script"))}async Ae(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Qb=A.map(g=>new g(this));this.nd();var d=a.bb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.kc)&&d.unshift(...a.kc);d=await Promise.all(d.map(g=>
this.Oa(g)));await Promise.all(d.map(g=>ja(g)));d=self.C3_ProjectScriptsStatus;const e=a.ad,f=a.jc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Oa(h),await ja(h),"preview"!==this.B||d[g]||this.rd(g,"main script did not run to completion")}catch(k){this.rd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Oa(h),await ja(h);"preview"===this.B&&"object"!==typeof self.ff.hf?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.od(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:xa}),Ca(this.ya),this.qd(),this.Ta=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ta,a))}rd(a,c){this.Lb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}qd(){this.Lb()}Lb(){const a=
window.Ue;a&&(a.parentElement.removeChild(a),window.Ue=null)}async De(){const a=await Da(this.sb);return{outputPort:a,transferables:[a]}}ze(){if(this.ca)throw Error("not available in worker mode");return this.Ta}Hb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ld(a,c,d,e,f){const g=wa++,h=new Promise((k,n)=>{va.set(g,{resolve:k,reject:n})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ee(a);if("result"===c)this.He(a);else if("runtime-ready"===c)this.Ie();else if("alert-error"===c)this.Lb(),alert(a.message);else if("creating-runtime"===c)this.qd();else throw Error(`unknown message '${c}'`);}Ee(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=sa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Kb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Kb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Kb(f,!1,""+h)}):this.Kb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Kb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}He(a){const c=a.responseId,d=a.isOk;a=a.result;const e=va.get(c);d?e.resolve(a):e.reject(a);va.delete(c)}C(a,
c,d){let e=sa.get(a);e||(e=new Map,sa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static va(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}nd(){for(const a of this.Qb)if("runtime"===a.mb){this.ya=a;return}throw Error("cannot find runtime DOM handler");}Fe(a){this.Hb("debugger","message",a)}Ie(){for(const a of this.Qb)a.cd()}static ib(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
za)}static sd(a){za=!!a}md(a){this.Ya.push(a);this.Ec()}Ke(a){a=this.Ya.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ya.splice(a,1);this.Ya.length||this.vc()}Ec(){-1===this.Za&&this.Ya.length&&(this.Za=requestAnimationFrame(this.Se))}vc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Ge(){this.Za=-1;for(const a of this.Ya)a();this.Ec()}Da(a){this.ya.Da(a)}Ma(a){this.ya.Ma(a)}Dc(){this.ya.Dc()}Jb(a){this.ya.Jb(a)}ne(){return!!na["audio/webm; codecs=opus"]}async Me(a){a=await this.ld("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}re(a){this.Pc=!0;this.Ad=a}le(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}kd(a){return!this.le(a)}async Oa(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Ub&&this.kd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Eb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ce(a){const c=a.filename;switch(a.as){case "text":return await this.ke(c);
case "buffer":return await this.Eb(c);default:throw Error("unsupported type");}}fd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ke(a){a=await this.fd(a);return await pa(a)}wc(){if(ra.length&&!(8<=y)){y++;var a=ra.shift();this.we(a.filename,a.bf,a.Ve)}}Eb(a){return new Promise((c,d)=>{ra.push({filename:a,bf:e=>{y--;this.wc();c(e)},Ve:e=>{y--;this.wc();d(e)}});this.wc()})}async we(a,c,d){try{const e=
await this.fd(a),f=await qa(e);c(f)}catch(e){d(e)}}Le(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ve(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.ue(c,d));await Promise.all(a)}async ue(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),
this.Xb[a]=c.str;else{let d=await this.ye(c);d||(d=this.xe(c));this.ra[a]=d}}async ye(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}xe(a){a=this.Je(a);return this.te(a.data,a.Ye)}Je(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ye:a,data:d}}te(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const B=self.oa;
function Ea(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Fa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),C={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ga={dispatchUserScriptEvent:!0},Ha={dispatchRuntimeEvent:!0};
function Ia(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ja(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function F(b){b=URL.createObjectURL(b);try{return await Ja(b)}finally{URL.revokeObjectURL(b)}}
function Ka(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function La(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await F(b);var d=await Ka(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await F(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await F(b)}
function Ma(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Na=new Set(["input","textarea","datalist","select"]),Oa=new Set(["canvas","body","html"]);function G(b){b.target.tagName&&Oa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Pa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await F(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await La(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Qa=!1;document.addEventListener("pause",()=>Qa=!0);document.addEventListener("resume",()=>Qa=!1);function Ca(b){b.zd=!0;b.Tc=b.v.pa();b.tb=b.v.ia()}async function Ra(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Sa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ta(b){return await self.C3_GetSvgImageSize(b.blob)}function Ua(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Va(b){self.setTimeout(()=>{b.yd=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Wa(b,!0)),document.addEventListener("resume",()=>Wa(b,!1))):document.addEventListener("visibilitychange",()=>Wa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Qa)}}
function Xa(b){b.ud||(b.ud=!0,window.addEventListener("deviceorientation",a=>{b.Z||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},C)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},C)}))}
function Ya(b){b.td||(b.td=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},C)}}))}async function Za(b){await Ia(b.url)}
function $a(b,a){b.Bd=a.message;-1===b.Jc&&(b.Jc=setTimeout(()=>{b.Jc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Bd)},250))}function H(b){if(!b.Z){var a=B.ib();a&&"any"!==b.Yc&&ab(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}function bb(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:B.ib(),innerWidth:b.pa(),innerHeight:b.ia()})}
function Wa(b,a){a?b.v.vc():b.v.Ec();l(b,"visibilitychange",{hidden:a})}function db(b,a,c){"Backspace"===c.key&&G(c);if(!b.Z){var d=Fa.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},C)}}
function eb(b,a,c,d){b.Z||Ea(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function gb(b){window!==window.top&&window.focus();hb(b.target)&&document.activeElement&&!hb(document.activeElement)&&document.activeElement.blur()}
function J(b,a,c){if(!b.Z){var d=0;"mouse"===c.pointerType&&(d=b.yb);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},C);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),eb(b,d,c,Ga),b.yb=c.buttons)}}
function ib(b,a,c){if(!b.Z&&!Ea(c)){var d=b.yb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},C);b.yb=c.buttons;eb(b,c.type,c,Ga)}}
function K(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
C)}}function jb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function kb(b,a,c,d){const e=b.pa(),f=b.ia();b.ab=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:B.ib()}):10>d&&lb(b,e,f,d+1)}
function lb(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>kb(b,a,c,d),48)}
function ab(b){b=b.Yc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function hb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
B.va(class extends self.fb{constructor(b){super(b,"runtime");this.Gd=!0;this.zd=!1;this.ab=-1;this.Yc="any";this.td=this.ud=!1;this.fc=document.createElement("div");this.fc.className="c3-screen-reader-text";this.fc.setAttribute("aria-live","polite");document.body.appendChild(this.fc);this.Ha=null;this.Z=!1;this.Bd="";this.Jc=-1;this.yd=!1;this.Tc=b.pa();this.tb=b.ia();this.da=this.Cb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Pc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Gd&&(e.style.display="",this.Gd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ra(d));b.C("runtime","raster-svg-image",d=>Sa(d));b.C("runtime","get-svg-image-size",
d=>Ta(d));b.C("runtime","set-target-orientation",d=>{this.Yc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ua(d));b.C("runtime","go-to-script",d=>Ua(d));b.C("runtime","before-start-ticking",()=>Va(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Xa(this));b.C("runtime","enable-device-motion",()=>Ya(this));b.C("runtime","add-stylesheet",d=>Za(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.fc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.H.style.display="";this.v.re(d.duration)});b.C("runtime","export-to-video-progress",d=>$a(this,d));b.C("runtime","exported-to-video",d=>{window.Te({type:"exported-video",
blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Te({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ma(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",G);window.addEventListener("gesturehold",G);c.addEventListener("selectstart",G);c.addEventListener("gesturehold",G);window.addEventListener("touchstart",
G,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",G,{passive:!1}),c.addEventListener("pointerdown",G)):c.addEventListener("touchstart",G);this.yb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Pa,{passive:!1});window.addEventListener("wheel",Pa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.zd){var d=this.pa();var e=this.ia();if(this.v.jd()){if(this.yd){if(this.Tc===d&&
e<this.tb){this.Cb=this.tb-e;jb(this,this.tb,this.Cb);d=void 0;break a}0<this.Cb&&(this.Cb=0,jb(this,e,this.Cb))}this.Tc=d;this.tb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:B.ib()});this.v.rc()&&(-1!==this.ab&&clearTimeout(this.ab),kb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",d=>bb(this,d));window.addEventListener("webkitfullscreenerror",d=>bb(this,d));window.addEventListener("mozfullscreenerror",d=>bb(this,d));if(b.rc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ma(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(B.sd(!0),H(this)):"exited-fullscreen"===d?(B.sd(!1),H(this)):console.warn("Unknown wrapper message: ",d)};this.Ua=new Set;this.Zb=new WeakSet;this.wa=!1}cd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Ha)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},Ha);this.yb=0});window.addEventListener("focusin",a=>{a=a.target;(Na.has(a.tagName.toLowerCase())||Ma(a))&&l(this,"keyboard-blur",null,Ha)});window.addEventListener("keydown",a=>db(this,"keydown",a));window.addEventListener("keyup",a=>db(this,"keyup",a));window.addEventListener("dblclick",a=>eb(this,"dblclick",a,C));window.addEventListener("wheel",a=>{this.Z||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},C)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{gb(a);J(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{J(this,"pointermove",a)}):window.addEventListener("pointermove",a=>J(this,"pointermove",a)),window.addEventListener("pointerup",a=>J(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>J(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{gb(a);ib(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>ib(this,"pointermove",a)),window.addEventListener("mouseup",a=>ib(this,"pointerup",a)),window.addEventListener("touchstart",a=>{gb(a);K(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>K(this,"pointermove",a)),window.addEventListener("touchend",a=>K(this,"pointerup",a)),window.addEventListener("touchcancel",a=>K(this,"pointercancel",a)));const b=
()=>this.Dc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.me()&&!this.v.jd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{jb(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.v.pa()}ia(){return this.v.ia()}Dc(){var b=
[...this.Ua];this.Ua.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Zb.has(a)||this.Ua.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");this.Zb.delete(b);let a;try{a=b.play()}catch(c){this.Ua.add(b);return}a&&a.catch(()=>{this.Zb.has(b)||this.Ua.add(b)})}Ma(b){this.Ua.delete(b);this.Zb.add(b)}Jb(b){this.wa=!!b}});"use strict";
async function Aa(b){if(b.Ne)throw Error("already initialised");b.Ne=!0;var a=b.za.yc(("playable-ad"===b.za.B?b.za.$a:"")+"dispatchworker.js");b.Hc=await b.za.mc(a,b.lb,{name:"DispatchWorker"});a=new MessageChannel;b.Oc=a.port1;b.Hc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Wc=await Da(b)}function Ba(b){return[b.Oc,b.Wc]}
async function Da(b){const a=b.Hd.length;var c=b.za.yc(("playable-ad"===b.za.B?b.za.$a:"")+"jobworker.js");c=await b.za.mc(c,b.lb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Hc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Hd.push(c);return e.port1}
self.pe=class{constructor(b){this.za=b;this.lb=b.ba;this.lb="preview"===b.B?this.lb+"workers/":this.lb+b.$a;this.Pe=Math.min(navigator.hardwareConcurrency||2,16);this.Hc=null;this.Hd=[];this.Wc=this.Oc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.oa({cf:!0,df:"workermain.js",bb:["scripts/c3runtime.js"],jc:[],ad:"",$e:"scripts/",kc:["box2d.wasm.js"],Ud:"html5"}));"use strict";
async function mb(b,a){a=a.type;let c=!0;0===a?c=await nb():1===a&&(c=await ob());l(b,"permission-result",{type:a,result:c})}async function nb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function ob(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.oa.va(class extends self.fb{constructor(b){super(b,"touch");q(this,"request-permission",a=>mb(this,a))}});"use strict";const pb=180/Math.PI;
async function qb(b,a){if(a.isiOSCordova||a.isSafari)b.bc=!0;b.Zc=a.timeScaleMode;b.Md=["equalpower","HRTF","soundfield"][a.panningModel];b.xd=["linear","inverse","exponential"][a.distanceModel];b.Nd=a.refDistance;b.Ld=a.maxDistance;b.Pd=a.rolloffFactor;if(b.v.Pc)b.bc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.Ad)});else{var c={latencyHint:a.latencyHint};b.Sd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");rb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&rb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
L(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function sb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,k=a.vol,n=a.pos,p=a.panning,D=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Id=g;tb(b,g);try{b.$=await ub(b,c,d,e,g,f);if(p){M(b.$,!0);var u=b.$,E=p.innerAngle,ta=p.outerAngle,ua=p.outerGain;if(u.rb){vb(u,p.x,p.y,p.z,p.angle);var I=self.cb.se;u.sa[0]!==I(E)&&(u.sa[0]=
I(E),u.F.coneInnerAngle=I(E));u.sa[1]!==I(ta)&&(u.sa[1]=I(ta),u.F.coneOuterAngle=I(ta));u.sa[2]!==ua&&(u.sa[2]=ua,u.F.coneOuterGain=ua)}p.hasOwnProperty("uid")&&(b.$.qa=p.uid)}else"number"===typeof D&&0!==D?(N(b.$,!0),wb(b.$,D)):(M(b.$,!1),N(b.$,!1));b.$.Play(h,k,n,z)}catch(Pb){console.error("[Construct] Audio: error starting playback: ",Pb);return}finally{c=b.Ab.get(g);if(!c)throw Error("expected pending tag");c.bd--;0===c.bd&&(c.resolve(),b.Ab.delete(g))}aa(b)}
async function xb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await yb(b,c);for(const p of O(b,c)){c=p;var f=d,g=e,h=a;if(!c.Sa){var k=c.G.gain;k.cancelScheduledValues(0);var n=c.s.g.currentTime;g=n+g;k.setValueAtTime(k.value,n);k.linearRampToValueAtTime(f,g);c.Ka=f;c.Ra=g;c.Rd=h}}P(b)}async function zb(b,a){const c=a.tag;a=a.rate;await yb(b,c);for(const d of O(b,c))b=d,b.ma!==a&&(b.ma=a,b.Fa())}
async function Ab(b,a){const c=a.tag;a=a.pos;await yb(b,c);for(const d of O(b,c))d.sc(a)}async function Bb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ub(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Cb(b,a){if(a=await L(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function Db(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.$d(b,...e);else if("delay"===c)e=new self.Yd(b,...e);else if("convolution"===c){c=null;try{c=await L(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Xd(b,c.ja,...e);var f=a.bufferType;c.vd=a.bufferOriginalUrl;c.wd=f}else if("flanger"===c)e=new self.ae(b,...e);else if("phaser"===c)e=new self.ce(b,...e);else if("gain"===c)e=
new self.be(b,...e);else if("stereopan"===c)e=new self.ee(b,...e);else if("tremolo"===c)e=new self.fe(b,...e);else if("ringmod"===c)e=new self.de(b,...e);else if("distortion"===c)e=new self.Zd(b,...e);else if("compressor"===c)e=new self.Wd(b,...e);else if("analyser"===c)e=new self.Vd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.la.get(d);e||(e=[],b.la.set(d,e));a.Fd=e.length;a.ga=d;e.push(a);Eb(b,d);Gb(b)}
async function Hb(b,a){try{const c=b.g.suspend(a.time);b.Ed?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Hb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ib(d)),b.Ed=!0);await c}catch(c){Ib(c)}}
function rb(b){b.Rb||(b.Nc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Rb=!0)}
async function L(b,a,c,d,e,f){for(var g of b.ka)if(g.hb()===c)return await Jb(g),g;if(f)return null;if(e&&(b.bc||b.Dd)){f=0;for(let h=0,k=b.ka.length;h<k;++h)g=b.ka[h],b.ka[f]=g,g.Ba()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Sd;e&&f&&(b.Dd=!0);c=!e||b.bc||f?new self.ie(b,a,c,d,e,f):new self.ge(b,a,c,d,e);b.ka.push(c);await Jb(c);b.Kd.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Kd.add(a));return c}
function Kb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.na()}function Eb(b,a){let c=b.na();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of O(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Uc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*O(b,a){if(a)for(const c of b.J)b=c.ga,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Lb(b,a,c){return c?b.v.Me(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Mb(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.O===a?f.j():++c}b.J.length=c}
async function ub(b,a,c,d,e,f){for(const g of b.J)if(g.hb()===c&&(g.lc()||f))return g.ga=e,g;a=await L(b,a,c,d,f);e="html5"===a.Fc?new self.he(a.s,a,e):new self.je(a.s,a,e);b.J.push(e);return e}function tb(b,a){let c=b.Ab.get(a);if(!c){let d=null;c={bd:0,promise:new Promise(e=>d=e),resolve:d};b.Ab.set(a,c)}c.bd++}function yb(b,a){a||(a=b.Id);return(b=b.Ab.get(a))?b.promise:Promise.resolve()}function P(b){if(0<b.Pa.size)aa(b);else for(const a of b.J)if(!a.I&&!a.U()){aa(b);break}}
function Nb(b,a,c,d){l(b,"trigger",{type:a,tag:c,aiid:d})}function Gb(b){b.Qc||(b.Qc=!0,Promise.resolve().then(()=>Ob(b)))}function Ob(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.gb());l(b,"fxstate",{fxstate:a});b.Qc=!1}
async function Qb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,k=a.isLooping,n=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ub(b,d,e,f,h,g)}catch(D){console.error("[Construct] Audio: error loading audio state: ",D);return}b=c;(d=a.pan)?(M(b,!0),e=b.F,f=d.pos,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],f=d.orient,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],e.setPosition(...b.Wa),e.setOrientation(...b.Va),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):M(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?N(b,!1):(N(b,!0),wb(b,d));c.Play(k,n,p,0);a.isPlaying||c.jb();c.Ac(a)}}}function Ib(b){console.error("[Audio] Offline rendering error: ",b)}
self.cb=class extends self.fb{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Rb=this.Nc=!1;this.Aa=()=>{if(!this.Nc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Rb&&(this.Nc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Rb=!1)}};this.ka=[];this.J=[];this.$=null;this.Id="";this.Kd=new Set;this.Jd=-1;this.Ab=new Map;this.Yb=1;this.wa=!1;this.Zc=0;this.hc=1;this.Kc=0;this.Md="HRTF";this.xd="inverse";this.Nd=600;this.Ld=1E4;this.Pd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Dd=this.bc=!1;this.Sd=this.v.ne();this.la=new Map;this.Pa=new Set;this.Ed=this.Qc=!1;this.Uc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Uc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Kb(this,this.Uc))};this.Pb=null;self.C3Audio_GetOutputStream=()=>{this.Pb||(this.Pb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Pb));return this.Pb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>qb(this,a)],["play",a=>sb(this,a)],["stop",a=>{a=a.tag;for(const c of O(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.J)a.Ca()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of O(this,c))a?d.jb():d.Ib();P(this)}],["set-volume",a=>
{const c=a.tag;a=a.vol;for(const d of O(this,c))Q(d,a)}],["fade-volume",a=>xb(this,a)],["set-master-volume",a=>{this.Yb=a.vol;this.Qa.gain.value=this.Yb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of O(this,c))Rb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.v.Jb(this.wa);for(const c of this.J)c.Mb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of O(this,c))d.tc(a)}],["set-playback-rate",a=>zb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of O(this,
c))N(d,!0),wb(d,a)}],["seek",a=>Ab(this,a)],["preload",a=>Bb(this,a)],["unload",a=>Cb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.J)c.uc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Db(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.la.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),Gb(this))}],["remove-effects",a=>
{a=a.tag.toLowerCase();const c=this.la.get(a);if(c&&c.length){for(const d of c)d.j();this.la.delete(a);Eb(this,a)}}],["tick",a=>{this.hc=a.timeScale;this.Kc=a.gameTime;this.Jd=a.tickCount;if(0!==this.Zc)for(var c of this.J)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==
c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.J)e.qa===a&&vb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>this.Cc(a)],["offline-render-audio",a=>Hb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Qa}Gb(){return this.wa}Da(b){this.v.Da(b)}Ma(b){this.v.Ma(b)}Na(){for(var b of this.Pa)b.Na();b=this.g.currentTime;for(var a of this.J)a.Na(b);
a=this.J.filter(c=>!c.I&&!c.U()).map(c=>c.gb());l(this,"state",{tickCount:this.Jd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.ga,index:c.Fd,peak:c.Xa,rms:c.Od,binCount:c.l.frequencyBinCount,freqBins:c.Cd}))});0===a.length&&0===this.Pa.size&&this.Sb&&(this.v.Ke(this.Td),this.Sb=!1)}async Cc(b){const a=b.saveLoadMode;if(3!==a){var c=[];for(var d of this.J)d.Ba()&&1===a||!d.Ba()&&2===a?c.push(d):d.j();this.J=c}for(const e of this.la.values())for(const f of e)f.j();
this.la.clear();this.hc=b.timeScale;this.Kc=b.gameTime;c=b.listenerPos;this.aa[0]=c[0];this.aa[1]=c[1];this.aa[2]=c[2];this.g.listener.setPosition(c[0],c[1],c[2]);c=b.listenerOrientation;if(Array.isArray(c)){for(d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}this.wa=b.isSilent;this.v.Jb(this.wa);this.Yb=b.masterVolume;this.Qa.gain.value=this.Yb;c=[];for(const e of Object.values(b.effects))c.push(Promise.all(e.map(f=>Db(this,f))));await Promise.all(c);await Promise.all(b.playing.map(e=>
Qb(this,e,a)));P(this)}static se(b){return b*pb}static gd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static qe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.oa.va(self.cb);"use strict";function Jb(b){b.Wb||(b.Wb=b.zc());return b.Wb}self.dd=class{constructor(b,a,c,d,e){this.s=b;this.Re=a;this.Ja=c;this.R=d;this.Oe=e;this.Fc="";this.Wb=null}j(){this.Wb=this.s=null}zc(){}V(){return this.s.V()}oc(){return this.Re}hb(){return this.Ja}nc(){return this.R}Ba(){return this.Oe}ha(){}};
"use strict";
self.ge=class extends self.dd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Fc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.ub=this.vb=null;this.M.addEventListener("canplaythrough",()=>!0);this.zb=this.V().createGain();this.xb=null;this.M.addEventListener("canplay",()=>{this.vb&&(this.vb(),this.ub=this.vb=null);!this.xb&&this.M&&(this.xb=this.V().createMediaElementSource(this.M),this.xb.connect(this.zb))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.ub&&(this.ub(f),this.ub=this.vb=null)})}j(){Mb(this.s,this);this.zb.disconnect();this.zb=null;this.xb.disconnect();this.xb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}zc(){return new Promise((b,a)=>{this.vb=b;this.ub=a;this.M.src=this.Ja})}T(){return this.M}ha(){return this.M.duration}};"use strict";
async function Sb(b){if(b.Ga)return b.Ga;var a=b.s.v;if("cordova"===a.B&&a.kd(b.Ja)&&a.Ub)b.Ga=await a.Eb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Tb(b){if(b.ja)return b.ja;b.ja=await Lb(b.s,b.Ga,b.Qe);b.Ga=null}
self.ie=class extends self.dd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Fc="webaudio";this.ja=this.Ga=null;this.Qe=!!f}j(){Mb(this.s,this);this.ja=this.Ga=null;super.j()}async zc(){try{await Sb(this),await Tb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Ub=0;
function M(b,a){a=!!a;b.rb!==a&&(b.rb=a,b.rb?(N(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Md,b.F.distanceModel=b.s.xd,b.F.refDistance=b.s.Nd,b.F.maxDistance=b.s.Ld,b.F.rolloffFactor=b.s.Pd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function N(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(M(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function wb(b,a){b.Vb&&b.Xc!==a&&(b.fa.pan.value=a,b.Xc=a)}function Q(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ra=-1;b.G.gain.value=b.pc()}function Rb(b,a){a=!!a;b.Sa!==a&&(b.Sa=a,b.Mb())}
function vb(b,a,c,d,e){if(b.rb){var f=b.Wa,g=b.Va,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function R(b){return b.Rc?b.s.Kc:performance.now()/1E3}
self.ed=class{constructor(b,a,c){this.s=b;this.O=a;this.ga=c;this.Nb=Ub++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.rb=!1;this.Wa=[0,0,0];this.Va=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Vb=!1;this.Xc=0;this.I=!0;this.X=this.ta=this.K=!1;this.Ka=1;this.Sa=!1;this.ma=1;b=this.s.Zc;this.Rc=1===b&&!this.Ba()||2===b;this.Ra=this.qa=-1;this.Rd=!1}j(){this.O=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}na(){return Kb(this.s,this.ga)}oc(){return this.O.oc()}hb(){return this.O.hb()}nc(){return this.O.nc()}Ba(){return this.O.Ba()}U(){}lc(){}IsPlaying(){return!this.I&&!this.K&&!this.U()}La(){}ha(){return this.O.ha()}Play(){}Ca(){}jb(){}Ib(){}Na(b){-1!==this.Ra&&b>=this.Ra&&(this.Ra=-1,this.Rd&&this.Ca(),Nb(this.s,"fade-ended",this.ga,this.Nb))}pc(){const b=this.Ka;return isFinite(b)?b:0}Gb(){return this.s.Gb()}Mb(){}tc(){}Fa(){}sc(){}uc(){}qc(){}gb(){var b=this.Nb,
a=this.ga,c=this.ha(),d=-1===this.Ra?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Wa,orient:this.Va,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.Ba(),isLooping:this.X,isMuted:this.Sa,resumePosition:this.qc(),pan:f,stereoPan:this.fa?this.Xc:
null}}Ac(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Fa());Rb(this,b.isMuted)}};"use strict";
self.he=class extends self.ed{constructor(b,a,c){super(b,a,c);this.O.zb.connect(this.G);this.O.onended=()=>this.Bc()}j(){this.Ca();this.O.zb.disconnect();super.j()}T(){return this.O.T()}Bc(){this.I=!0;this.qa=-1;Nb(this.s,"ended",this.ga,this.Nb)}U(){return this.T().ended}lc(){return this.I?!0:this.U()}La(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);Q(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.hb()}' to position '${c}': `,e)}this.s.Da(d);this.K=this.I=!1;this.X=b;this.ma=1}Ca(){const b=this.T();b.paused||b.pause();this.s.Ma(b);this.I=!0;this.K=!1;this.qa=-1}jb(){if(!(this.K||this.I||this.U())){var b=this.T();b.paused||b.pause();this.s.Ma(b);this.K=!0}}Ib(){!this.K||this.I||this.U()||(this.s.Da(this.T()),this.K=!1)}Mb(){this.T().muted=this.Sa||this.Gb()}tc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Fa(){let b=this.ma;this.Rc&&(b*=this.s.hc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}sc(b){if(!this.I&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}qc(){return this.La()}uc(b){b?this.IsPlaying()?(this.T().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.s.Da(this.T()),this.ta=!1)}};"use strict";function S(b){b.o&&b.o.disconnect();b.o=null;b.kb=null}
self.je=class extends self.ed{constructor(b,a,c){super(b,a,c);this.o=null;this.$b=d=>this.Bc(d);this.Mc=!0;this.kb=null;this.P=this.ac=this.cc=0;this.Vc=1}j(){this.Ca();S(this);this.$b=null;super.j()}Bc(b){this.K||this.ta||b.target!==this.kb||(this.I=this.Mc=!0,this.qa=-1,S(this),Nb(this.s,"ended",this.ga,this.Nb))}U(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Mc}lc(){return!this.o||this.I?!0:this.U()}La(){let b;b=this.K?this.P:this.ac+(R(this)-this.cc)*this.ma;this.X||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Vc=1;Q(this,a);S(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ja;this.o.connect(this.G);this.kb=this.o;this.o.onended=this.$b;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Mc=!1;this.X=b;this.ma=1;this.cc=R(this);this.ac=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}jb(){this.K||this.I||this.U()||(this.P=this.La(),this.X&&(this.P%=this.ha()),this.K=!0,this.o.stop(0))}Ib(){!this.K||this.I||this.U()||(S(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.kb=this.o,this.o.onended=this.$b,this.o.loop=this.X,Q(this,this.Ka),this.Fa(),this.o.start(0,this.P),this.cc=R(this),this.ac=this.P,this.K=!1)}pc(){return super.pc()*this.Vc}Mb(){this.Vc=this.Sa||this.Gb()?0:1;Q(this,this.Ka)}tc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Fa(){let b=this.ma;this.Rc&&(b*=this.s.hc);this.o&&(this.o.playbackRate.value=b)}sc(b){this.I||this.U()||(this.K?this.P=b:(this.jb(),this.P=
b,this.Ib()))}qc(){return this.P}uc(b){b?this.IsPlaying()?(this.ta=!0,this.P=this.La(),this.X&&(this.P%=this.ha()),this.o.stop(0)):this.ta=!1:this.ta&&(S(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.kb=this.o,this.o.onended=this.$b,this.o.loop=this.X,Q(this,this.Ka),this.Fa(),this.o.start(0,this.P),this.cc=R(this),this.ac=this.P,this.ta=!1)}Ac(b){super.Ac(b);this.P=b.resumePosition}};"use strict";function T(b){return b.g.createGain()}
function U(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class V{constructor(b){this.s=b;this.g=b.V();this.Fd=-1;this.R=this.ga="";this.m=null}j(){this.g=null}N(){}S(){}gb(){return{type:this.R,tag:this.ga,params:this.m}}}
self.$d=class extends V{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.u=T(this);this.i=T(this);this.i.gain.value=g;this.h=T(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;U(this,this.i.gain,a,c,d);U(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;U(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;U(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;U(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,U(this,this.D.gain,a,c,d)}}};
self.Yd=class extends V{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.u=T(this);this.i=T(this);this.i.gain.value=d;this.h=T(this);this.h.gain.value=1-d;this.wb=T(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.ob=T(this);this.ob.gain.value=c;this.u.connect(this.wb);this.u.connect(this.h);this.wb.connect(this.i);this.wb.connect(this.W);this.W.connect(this.ob);this.ob.connect(this.wb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.wb.disconnect();
this.W.disconnect();this.ob.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){const e=self.cb.gd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;U(this,this.i.gain,a,c,d);U(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);U(this,this.ob.gain,e(a),c,d);break;case 5:this.m[0]=a,U(this,this.W.delayTime,a,c,d)}}};
self.Xd=class extends V{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.wd=this.vd="";this.u=T(this);this.i=T(this);this.i.gain.value=d;this.h=T(this);this.h.gain.value=1-d;this.nb=this.g.createConvolver();this.nb.normalize=c;this.nb.buffer=a;this.u.connect(this.nb);this.u.connect(this.h);this.nb.connect(this.i)}j(){this.u.disconnect();this.nb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,U(this,this.i.gain,a,c,d),U(this,this.h.gain,1-a,c,d)}}gb(){const b=super.gb();b.bufferOriginalUrl=this.vd;b.bufferUrl="";b.bufferType=this.wd;return b}};
self.ae=class extends V{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.u=T(this);this.h=T(this);this.h.gain.value=1-f/2;this.i=T(this);this.i.gain.value=f/2;this.qb=T(this);this.qb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=T(this);this.L.gain.value=c;this.u.connect(this.W);this.u.connect(this.h);this.W.connect(this.i);this.W.connect(this.qb);this.qb.connect(this.W);this.A.connect(this.L);
this.L.connect(this.W.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.W.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.qb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;U(this,this.i.gain,a/2,c,d);U(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;U(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;U(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,U(this,this.qb.gain,a/100,c,d)}}};
self.ce=class extends V{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.u=T(this);this.h=T(this);this.h.gain.value=1-g/2;this.i=T(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=T(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;U(this,this.i.gain,a/2,c,d);U(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;U(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;U(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;U(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;U(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,U(this,this.A.frequency,a,c,d)}}};self.be=class extends V{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=T(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.cb.gd;switch(b){case 4:this.m[0]=e(a),U(this,this.l.gain,e(a),c,d)}}};
self.ee=class extends V{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,U(this,this.l.pan,a,c,d)}}};
self.fe=class extends V{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=T(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=T(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;U(this,this.l.gain,1-a/2,c,d);U(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,U(this,this.A.frequency,a,c,d)}}};
self.de=class extends V{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.u=T(this);this.i=T(this);this.i.gain.value=c;this.h=T(this);this.h.gain.value=1-c;this.Bb=T(this);this.Bb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.Bb.gain);this.A.start(0);this.u.connect(this.Bb);this.u.connect(this.h);this.Bb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.Bb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;U(this,this.i.gain,a,c,d);U(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,U(this,this.A.frequency,a,c,d)}}};
self.Zd=class extends V{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.u=T(this);this.ec=T(this);this.dc=T(this);b=d;.01>b&&(b=.01);this.ec.gain.value=b;this.dc.gain.value=Math.pow(1/b,.6)*e;this.i=T(this);this.i.gain.value=f;this.h=T(this);this.h.gain.value=1-f;this.ic=this.g.createWaveShaper();this.Gc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Gc[32768+e]=f,this.Gc[32768-
e-1]=-f;this.ic.curve=this.Gc;this.u.connect(this.ec);this.u.connect(this.h);this.ec.connect(this.ic);this.ic.connect(this.dc);this.dc.connect(this.i)}j(){this.u.disconnect();this.ec.disconnect();this.ic.disconnect();this.dc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,U(this,this.i.gain,a,c,d),U(this,this.h.gain,
1-a,c,d)}}};self.Wd=class extends V{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Vd=class extends V{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Cd=new Float32Array(this.l.frequencyBinCount);this.Qd=new Uint8Array(a);this.Od=this.Xa=0;b=this.s;b.Pa.add(this);P(b)}j(){this.s.Pa.delete(this);this.l.disconnect();super.j()}Na(){this.l.getFloatFrequencyData(this.Cd);this.l.getByteTimeDomainData(this.Qd);const b=this.l.fftSize;let a=this.Xa=0;for(var c=0;c<b;++c){let d=(this.Qd[c]-
128)/128;0>d&&(d=-d);this.Xa<d&&(this.Xa=d);a+=d*d}c=self.cb.qe;this.Xa=c(this.Xa);this.Od=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";function W(b){b.stopPropagation()}
self.oa.va(class extends self.Fb{constructor(b){super(b,"button")}eb(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",W);d.addEventListener("pointermove",
W);d.addEventListener("pointerrawupdate",W);d.addEventListener("pointerup",W);d.addEventListener("mousedown",W);d.addEventListener("mouseup",W);d.addEventListener("keydown",W);d.addEventListener("keyup",W);c.addEventListener("click",()=>w(this,"click",b,{isChecked:c.checked}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Ea(d,a);return d}xc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}Ea(b,a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;
c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";function Vb(b){b.replaceChildren?b.replaceChildren():b.innerHTML=""}function Wb(b,a){b.innerHTML=a;Xb(b)}
function Xb(b){b=Array.from(b.querySelectorAll("script:not([c3-executed])"));for(const d of b){b=d.parentNode;var a=b.replaceChild,c=d;const e=document.createElement("script");e.text=c.text;c=c.attributes;for(let f=0,g=c.length;f<g;++f){const h=c[f];e.setAttribute(h.name,h.value)}e.setAttribute("c3-executed","");a.call(b,e,d)}}function X(b,a,c){return a?c?Array.from(b.querySelectorAll(a)):(b=b.querySelector(a))?[b]:[]:[b]}
function Y(b){return b?{isOk:!0,html:b.innerHTML,text:b.textContent}:{isOk:!1}}
self.oa.va(class extends self.Fb{constructor(b){super(b,"html-element");t(this,"set-content",(a,c)=>{{const e=c.str,f=c.type,g=c.selector;c=c["is-all"];try{const h=X(a,g,c);if(0===h.length)var d=Y(null);else{for(const k of h)"html"===f?Wb(k,e):k.textContent=e;d=Y(a)}}catch(h){console.warn("[HTML element] Failed to set content: ",h),d=Y(null)}}return d});t(this,"insert-content",(a,c)=>{{const f=c.str,g=c.type,h=c["at-end"]?"beforeend":"afterbegin";var d=c.selector;c=c["is-all"];try{const k=X(a,d,c);
if(0===k.length)var e=Y(null);else{for(const n of k)"html"===g?(d=n,d.insertAdjacentHTML(h,f),Xb(d)):n.insertAdjacentText(h,f);e=Y(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),e=Y(null)}}return e});t(this,"remove-content",(a,c)=>{{const e=c["is-clear"],f=c.selector;c=c["is-all"];if(f)try{const g=X(a,f,c);if(0===g.length)var d=Y(null);else{for(const h of g)e?Vb(h):h.remove();d=Y(a)}}catch(g){console.warn("[HTML element] Failed to remove content: ",g),d=Y(null)}else Vb(a),
d=Y(a)}return d});t(this,"set-content-class",(a,c)=>{{const e=c.mode,f=c["class-array"],g=c.selector;c=c["is-all"];try{const h=X(a,g,c);if(0===h.length)var d=Y(null);else{for(const k of h)for(const n of f)switch(e){case "add":k.classList.add(n);break;case "toggle":k.classList.toggle(n);break;case "remove":k.classList.remove(n)}d=Y(a)}}catch(h){console.warn("[HTML element] Failed to set class: ",h),d=Y(null)}}return d});t(this,"set-content-attribute",(a,c)=>{{const e=c.mode,f=c.attribute,g=c.value,
h=c.selector;c=c["is-all"];try{const k=X(a,h,c);if(0===k.length)var d=Y(null);else{for(const n of k)switch(e){case "set":n.setAttribute(f,g);break;case "remove":n.removeAttribute(f)}d=Y(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=Y(null)}}return d});t(this,"set-content-css-style",(a,c)=>{{const e=c.prop,f=c.value,g=c.selector;c=c["is-all"];try{const h=X(a,g,c);if(0===h.length)var d=Y(null);else{for(const k of h)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;
d=Y(a)}}catch(h){console.warn("[HTML element] Failed to set style: ",h),d=Y(null)}}return d});t(this,"get-element-box",(a,c)=>{(a=(c=c.selector)?a.querySelector(c):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});t(this,"insert-img-element",(a,c)=>{a:{const e=c.blobUrl;var d=c.width;const f=c.height,g=c.selector,h=c.insertAt;let k=a;if(g&&(k=a.querySelector(g),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;c.id&&(d.id=c.id);
c["class"]&&(d.className=c["class"]);0===h?k.prepend(d):1===h?k.append(d):k.replaceChildren?k.replaceChildren(d):(Vb(k),k.append(d));a=Y(a)}return a});t(this,"set-scroll-position",(a,c)=>{a:{const d=c.selector,e=c.direction;c=c.position;if(d&&(a=a.querySelector(d),!a)){c=void 0;break a}"left"===e?a.scrollLeft=c:a.scrollTop=c;c=void 0}return c})}eb(b,a){const c=document.createElement(a.tag);a["style-attribute"]&&c.setAttribute("style",a["style-attribute"]);c.style.position="absolute";var d=a["stop-input-events-mode"];
if(0<d){let e=null;1===d?e=f=>{f.target!==c&&f.stopPropagation()}:2===d&&(e=f=>f.stopPropagation());c.addEventListener("pointerdown",e);c.addEventListener("pointermove",e);c.addEventListener("pointerrawupdate",e);c.addEventListener("pointerup",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("dblclick",e)}a["allow-context-menu"]&&c.addEventListener("contextmenu",e=>e.stopPropagation());c.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===
typeof e.id?e.id:"",targetClass:"string"===typeof e.className?e.className:""});if(e===c)break;e=e.parentNode}w(this,"click",b,{chain:f})});c.addEventListener("animationend",e=>{const f=e.target;w(this,"animationend",b,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(c.id=a.id);a.className&&(c.className=a.className);a["css-color"]&&(c.style.color=a["css-color"]);a["css-background-color"]&&(c.style.backgroundColor=
a["css-background-color"]);a["allow-text-selection"]||(c.style.userSelect="none",c.style.webkitUserSelect="none");d=a.str;"html"===a.type?Wb(c,d):c.textContent=d;w(this,"initial-content",b,{html:c.innerHTML,text:c.textContent});return c}Ea(b,a){Wb(b,a.html)}});"use strict";function Yb(b,a,c){Zb(b,a,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));b.Tb=!0}function Zb(b,a,c){a.src&&a.src.startsWith("blob:")&&b.Tb&&URL.revokeObjectURL(a.src);a.src=c}
self.oa.va(class extends self.Fb{constructor(b){super(b,"iframe");this.Tb=!1;t(this,"navigate-url",(a,c)=>{Zb(this,a,c.url);this.Tb=!1});t(this,"display-html",(a,c)=>Yb(this,a,c))}eb(b,a){b=document.createElement("iframe");b.style.position="absolute";b.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(b.setAttribute("noresize","noresize"),b.setAttribute("scrolling","no"));a.isVisible||
(b.style.display="none");a.id&&(b.id=a.id);a.allow&&(b.setAttribute("allow",a.allow),a.allow.includes("fullscreen")&&b.setAttribute("allowfullscreen",""));a.enableSandbox&&b.setAttribute("sandbox",a.sandbox);a.url?b.src=a.url:a.html&&Yb(this,b,a);return b}Ea(){}hd(b){Zb(this,b,"");this.Tb=!1}});"use strict";function Z(b){b.stopPropagation()}function $b(b){const a=document.createElement("option");a.text=b;return a}
function ac(b){const a=b.selectedIndex,c=[];for(let d=0,e=b.length;d<e;++d)b.options[d].selected&&c.push(d);return{selectedIndex:a,selectedIndices:c}}
self.oa.va(class extends self.Fb{constructor(b){super(b,"list");t(this,"set-selected-index",(a,c)=>{a.selectedIndex=c.selectedIndex});t(this,"add-item",(a,c)=>{const d=c.index;c=$b(c.text);0>d?a.add(c):a.add(c,d)});t(this,"remove-item",(a,c)=>{a.remove(c.index)});t(this,"set-item",(a,c)=>{a.options[c.index].text=c.text});t(this,"clear",a=>{a.innerHTML=""});t(this,"load-state",(a,c)=>this.Cc(a,c))}eb(b,a){const c=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position=
"absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;c||(f.size=2);for(const g of e)f.add($b(g));f.addEventListener("pointerdown",Z);f.addEventListener("pointermove",Z);f.addEventListener("pointerrawupdate",Z);f.addEventListener("pointerup",Z);f.addEventListener("mousedown",Z);f.addEventListener("mouseup",Z);f.addEventListener("click",g=>{g.stopPropagation();w(this,"click",b,ac(f))});f.addEventListener("dblclick",g=>{g.stopPropagation();w(this,"dblclick",b,ac(f))});f.addEventListener("change",
()=>da(this,"change",b,ac(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.Ea(f,a);return f}Ea(b,a){b.title=a.title;b.disabled=!a.isEnabled;b.multiple=!!a.isMultiSelect}Cc(b,a){b.innerHTML="";for(const c of a.items)b.add($b(c));b.selectedIndex=a.selectedIndex;for(const c of a.selectedIndices)if(a=b.options[c])a.selected=!0}});"use strict";
self.oa.va(class extends self.fb{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.H.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
